### ISSUE TITLE
no reconoce el comando sphinx-quickstart

### ISSUE THREAD

**Issue by danimaniarqsoft** [robertovillarejo/DADS-template-docs#1]
Buena noche,

Al ejecutar el comando de sphinx-quickstart me aparece el siguiente error:

`zsh: command not found: sphinx-quickstart
`
seguí los siguientes pasos:

- Instalación de Sphinx:  
  `pip install sphinx sphinx-autobuild`

- Instalación de recommonmark:  
  `pip install recommonmark`

Gracias.

**Comment by robertovillarejo** [comment]
Probablemente sea a causa de la versión del pip, con la 9.0.1 funciona bien.
Para ver la versión del pip:
`pip --version`

Para actualizar, prueba con lo siguiente ([Fuente](https://pip.pypa.io/en/stable/installing/#upgrade-pip)):
`wget https://bootstrap.pypa.io/get-pip.py`
`python get-pip.py`

Y trata de instalar de nuevo:
`pip install sphinx sphinx-autobuild`
`pip install recommonmark`

**Comment by danimaniarqsoft** [comment]
Ya teminé e actualizar a la nueva versión. Al parecer el tema es que no reconoce la instrucción "sphinx-quickstart", ya que si la ejecuto sin otro contexto sigue apareciendo el mismo error:

`zsh: command not found: sphinx-quickstart
`

**Comment by danimaniarqsoft** [comment]
Finalmente cerrado
